# Generated by Django 3.2 on 2022-09-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='barrio',
            field=models.ManyToManyField(blank=True, null=True, to='zonas.Barrio'),
        ),
        migrations.AddField(
            model_name='documento',
            name='referenciadescriptiva',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
