# Generated by Django 3.2 on 2022-09-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonas', '0001_initial'),
        ('documentos', '0002_auto_20220915_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='barrio',
            field=models.ManyToManyField(to='zonas.Barrio'),
        ),
    ]
